### ISSUE TITLE
add-path is deprecated

### ISSUE THREAD

**Issue by nafg** [yilinwei/setup-ammonite#3]
Using this action fails with:

> Error: Unable to process command '::add-path::/opt/hostedtoolcache/amm/.amm-bin/x64' successfully.
> Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by yilinwei** [comment]
@nafg 

Apologies; my github notifications have been a bit weird recently. Do you still need this?

EDIT: Took a look at the dependencies on the repo - will fix this ASAP. Thanks for raising the issue.

**Comment by yilinwei** [comment]
Fixed in #4.
